services:
  
  client:
    build:
      context: ./packages/client
    volumes:
      - staticbuild:/app/out
 
  nginx:
    build:
      context: ./.nginx
    volumes:
      - staticbuild:/app/public
    ports:
      - 3000:3000
      