import { AppBar, Button } from '@mui/material';
import Head from 'next/head';
import { useContext } from 'react';
import { ColorModeContext } from '@/theme/theme-mode';

export default function Home() {
  const { toggleColorMode } = useContext(ColorModeContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <AppBar />
        <Button variant='contained' onClick={toggleColorMode}>
          Mode
        </Button>
      </main>
    </>
  );
}
